name: Build and Release DEB

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        docker pull ghcr.io/theos/theos:latest

    - name: Build DEB using Theos Docker
      run: |
        docker run --rm -v ${{ github.workspace }}:/theos -w /theos           -e THEOS=/theos/theos           ghcr.io/theos/theos:latest           make clean package FINALPACKAGE=1

    - name: Upload DEB to Release
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
